version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file: .env
    volumes:
      - .:/usr/src/app
    command: [ "yarn", "start" ]
